// eslint-disable-next-line no-unused-vars
const authmanagement = require('./authmanagement/authmanagement.service.js');
const configs = require('./configs/configs.service.js');
const mailer = require('./mailer/mailer.service.js');
const users = require('./users/users.service.js');
const participantCategories = require('./participantCategories/participantCategories.service.js');
const paymentGroups = require('./paymentGroups/paymentGroups.service.js');
const profiles = require('./profiles/profiles.service.js');
const documentTypes = require('./documentTypes/documentTypes.service.js');
const diaries = require('./diaries/diaries.service.js');
const documents = require('./documents/documents.service.js');
const snippets = require('./snippets/snippets.service.js');
const transcriptions = require('./transcriptions/transcriptions.service.js');
const transcriptSentences = require('./transcriptSentences/transcriptSentences.service.js');
const transcriptMaintenance = require('./transcriptMaintenance/transcriptMaintenance.service.js');
const adminMaintenance = require('./adminMaintenance/adminMaintenance.service.js');
const reporting = require('./reporting/reporting.service.js');
const subjects = require('./subjects/subjects.service.js');
const subjectMaintenance = require('./subjectMaintenance/subjectMaintenance.service.js');
const diaryPayPeriods = require('./diaryPayPeriods/diaryPayPeriods.service.js');
const dictionaryWords = require('./dictionaryWords/dictionaryWords.service.js');
const remoteWorkers = require('./remoteWorkers/remoteWorkers.service.js');
const processing = require('./processing/processing.service.js');
const processingJobs = require('./processingJobs/processingJobs.service.js');
const transcriptionManager = require('./transcriptionManager/transcriptionManager.service.js');
module.exports = function (app) {
  app.configure(configs);
  app.configure(mailer);
  app.configure(users);
  app.configure(participantCategories);
  app.configure(paymentGroups);
  app.configure(profiles);
  app.configure(authmanagement);
  app.configure(documentTypes);
  app.configure(diaries);
  app.configure(documents);
  app.configure(snippets);
  app.configure(transcriptions);
  app.configure(transcriptSentences);
  app.configure(transcriptMaintenance);
  app.configure(adminMaintenance);
  app.configure(reporting);
  app.configure(subjects);
  app.configure(subjectMaintenance);
  app.configure(diaryPayPeriods);
  app.configure(dictionaryWords);
  app.configure(remoteWorkers);
  app.configure(processing);
  app.configure(processingJobs);
  app.configure(transcriptionManager);
};
